log-slots: 7
no-access-log: false
access-log-slots: 16
byoc: false
use-cert: false
trusted-x-forwarded-for: false
public-host: ""
public-port: 0
port: 4000
cluster-id: ${CLUSTER_ID}
cluster-secret: ${CLUSTER_SECRET}
sync-interval: 10
only-gc-when-start: false
download-max-conn: 16
max-reconnect-count: 10
certificates:
  - cert: /path/to/cert.pem
    key: /path/to/key.pem
tunneler:
  enable: false
  tunnel-program: ./path/to/tunnel/program
  output-regex: \bNATedAddr\s+(?<host>[0-9.]+|\[[0-9a-f:]+\]):(?<port>\d+)$
  tunnel-timeout: 0
cache:
  type: inmem
serve-limit:
  enable: false
  max-conn: 16384
  upload-rate: 10240
dashboard:
  enable: true
  username: ""
  password: ""
  pwa-name: GoOpenBmclApi Dashboard
  pwa-short_name: GOBA Dash
  pwa-description: Go-Openbmclapi Internal Dashboard
  notification-subject: mailto:user@example.com
database:
  driver: sqlite
  data-source-name: files.db
hijack:
  enable: false
  enable-local-cache: false
  local-cache-path: hijack_cache
  require-auth: false
  auth-users:
    - username: example-username
      password: example-password
storages:
  - type: local
    id: local-storage-0
    weight: 100
    data:
      cache-path: _cache
      compressor: ""
webdav-users:
  example-user:
    endpoint: https://webdav.example.com/path/to/endpoint/
    username: example-username
    password: example-password
advanced:
  debug-log: false
  socket-io-log: false
  no-heavy-check: false
  no-gc: false
  heavy-check-interval: 120
  keepalive-timeout: 10
  skip-first-sync: false
  skip-signature-check: false
  no-fast-enable: false
  wait-before-enable: 0
  do-NOT-redirect-https-to-SECURE-hostname: false
  do-not-open-faq-on-windows: false
